CREATE USER flyway WITH PASSWORD 'miamiconfirmedittome';

--CREATE DATABASE posts;
GRANT ALL PRIVILEGES ON DATABASE posts TO ynet, flyway;

REVOKE ALL ON DATABASE posts FROM PUBLIC;

\c posts;

CREATE SCHEMA posts AUTHORIZATION ynet;
GRANT ALL ON SCHEMA posts TO ynet, flyway;
REVOKE ALL ON SCHEMA posts FROM PUBLIC;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

ALTER ROLE ynet SET search_path TO posts, public;

ALTER DEFAULT PRIVILEGES IN SCHEMA posts GRANT ALL ON TABLES TO ynet, flyway;
ALTER DEFAULT PRIVILEGES IN SCHEMA posts GRANT USAGE, SELECT ON SEQUENCES TO ynet, flyway;
