#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL

CREATE ROLE ${FLYWAY_USER}
  LOGIN
  PASSWORD '${FLYWAY_PASSWORD}';

CREATE DATABASE ${POSTS_DB_NAME};

-- Revoke default permissions
REVOKE ALL ON DATABASE ${USERS_DB_NAME} FROM PUBLIC;
REVOKE ALL ON DATABASE ${POSTS_DB_NAME} FROM PUBLIC;

-- DB-level permissions
GRANT ALL PRIVILEGES ON DATABASE ${USERS_DB_NAME} TO ${POSTGRES_USER};
GRANT CONNECT ON DATABASE ${USERS_DB_NAME} TO ${FLYWAY_USER};

GRANT ALL PRIVILEGES ON DATABASE ${POSTS_DB_NAME} TO ${POSTGRES_USER};
GRANT CONNECT ON DATABASE ${POSTS_DB_NAME} TO ${FLYWAY_USER};

\c ${USERS_DB_NAME};

CREATE SCHEMA ${USERS_DB_NAME} AUTHORIZATION ${POSTGRES_USER};

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA ${USERS_DB_NAME} FROM PUBLIC;

-- Total control over users schema
GRANT ALL ON SCHEMA ${USERS_DB_NAME} TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${USERS_DB_NAME}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${USERS_DB_NAME}
  GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_USER};

-- Grant usage and creations permissions to flyway user
GRANT USAGE, CREATE ON SCHEMA ${USERS_DB_NAME} TO ${FLYWAY_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${USERS_DB_NAME}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${FLYWAY_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${USERS_DB_NAME}
  GRANT USAGE, SELECT ON SEQUENCES TO ${FLYWAY_USER};

-- Set search_path for the main user
ALTER ROLE ${POSTGRES_USER} IN DATABASE ${USERS_DB_NAME}
  SET search_path TO ${USERS_DB_NAME}, public;

\c ${POSTS_DB_NAME};

CREATE SCHEMA ${POSTS_DB_NAME} AUTHORIZATION ${POSTGRES_USER};

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA ${POSTS_DB_NAME} FROM PUBLIC;

-- Total control over posts schema
GRANT ALL ON SCHEMA ${POSTS_DB_NAME} TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${POSTS_DB_NAME}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${POSTS_DB_NAME}
  GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_USER};

-- Grant usage and creations permissions to flyway user
GRANT USAGE, CREATE ON SCHEMA ${POSTS_DB_NAME} TO ${FLYWAY_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${POSTS_DB_NAME}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${FLYWAY_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${POSTS_DB_NAME}
  GRANT USAGE, SELECT ON SEQUENCES TO ${FLYWAY_USER};

-- Set search_path for the main user
ALTER ROLE ${POSTGRES_USER} IN DATABASE ${POSTS_DB_NAME}
  SET search_path TO ${POSTS_DB_NAME}, public;

EOSQL