CREATE USER flyway WITH PASSWORD 'miamiconfirmedittome';

GRANT ALL PRIVILEGES ON DATABASE users TO ynet, flyway;
REVOKE ALL ON DATABASE users FROM PUBLIC;

CREATE DATABASE posts;
GRANT ALL PRIVILEGES ON DATABASE posts TO ynet, flyway;
REVOKE ALL ON DATABASE posts FROM PUBLIC;

\c users;

CREATE SCHEMA users AUTHORIZATION ynet;
GRANT ALL ON SCHEMA users TO ynet, flyway;
REVOKE ALL ON SCHEMA users FROM PUBLIC;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

ALTER ROLE ynet SET search_path TO users, public;

ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT ALL ON TABLES TO ynet, flyway;
ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT USAGE, SELECT ON SEQUENCES TO ynet, flyway;

\c posts;

CREATE SCHEMA posts AUTHORIZATION ynet;
GRANT ALL ON SCHEMA posts TO ynet, flyway;
REVOKE ALL ON SCHEMA posts FROM PUBLIC;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

ALTER ROLE ynet SET search_path TO posts, public;

ALTER DEFAULT PRIVILEGES IN SCHEMA posts GRANT ALL ON TABLES TO ynet, flyway;
ALTER DEFAULT PRIVILEGES IN SCHEMA posts GRANT USAGE, SELECT ON SEQUENCES TO ynet, flyway;
